[phases.setup]
aptPkgs = ['libglib2.0-0']  # Minimal for opencv-python-headless

[phases.install]
cmds = [
  'python -m venv --copies /opt/venv',
  '. /opt/venv/bin/activate && pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu'
]